// frontend/src/components/cards/BookCard.vue
<script setup lang="ts">
import type { Book } from "@/types/Book"
import type { Review } from "@/types/Review"
import { deleteReviewById } from "@/api/reviewService"

const { review } = defineProps<{
  book: Book
  review?: Review
  isUser?: boolean
}>()

const handleDeleteReview = async () => {
  try {
    await deleteReviewById(review!.id)
    alert("Deleted!")
    location.reload()
  } catch (error: any) {
    alert("Some error")
  }
}
</script>

<template>
  <div class="grid grid-cols-1 gap-6 p-2">
    <div
      class="bg-gray-800 rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300 group"
    >
      <div class="p-4">
        <div class="flex items-center">
          <img :src="book.image" alt="Book Cover" class="w-16 h-24 rounded-md mr-4" />
          <div class="flex-1">
            <h3 class="text-lg font-semibold">
              <router-link
                :to="`/books/${book.isbn}`"
                class="text-lg font-semibold text-blue-500 hover:underline"
              >
                {{ book.title }}
              </router-link>
              by {{ book.author }}
            </h3>
            <template v-if="review">
              <p class="text-sm mt-1">Reviewed by: {{ review.username }}</p>
              <p class="text-sm mt-1">
                Rating:
                <span class="text-yellow-500 font-bold">{{ review.rating }}</span>
              </p>
              <p class="text-sm mt-2">{{ review.comment }}</p>
              <p class="text-xs text-gray-400 mt-4">
                Reviewed {{ new Date(review.createdAt).toLocaleDateString() }}
              </p>
              <button
                v-if="isUser"
                class="bg-red-600 text-white text-xs px-2 py-1 rounded hover:bg-red-700 focus:outline-none opacity-0 group-hover:opacity-100 transition-opacity duration-300"
                @click="handleDeleteReview"
              >
                Delete
              </button>
            </template>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend-app/src/book/BookCard.tsx
import React, { useEffect, useState } from "react"
import { Link, useParams } from "react-router-dom"
import { BookResponse } from "./BookResponse"
import { deleteBookById, getBookById } from "../api/BookApi"
import threeDots from "../img/3-dots-icon-29.png"
import { TailSpin } from "react-loader-spinner"

interface BookDetailsProps {
  initialBook?: BookResponse
}

const BookCard: React.FC<BookDetailsProps> = ({ initialBook }) => {
  const { bookId } = useParams()
  const [book, setBook] = useState(initialBook)
  const [isHovered, setIsHovered] = useState(false)

  const getDateFromId = (id: string) => {
    const timestamp = parseInt(id.substring(0, 8), 16) * 1000
    return new Date(timestamp).toLocaleDateString()
  }

  useEffect(() => {
    if (!initialBook) {
      getBookById(bookId!)
        .then((response) => {
          setBook(response.data)
        })
        .catch((error) => {
          console.error("Error fetching book:", error)
        })
    }
  }, [bookId, initialBook])

  if (!book)
    return (
      <div className="flex justify-center">
        <TailSpin color="#00BFFF" height={50} width={50} />
      </div>
    )

  return (
    <div className="mx-auto max-w-lg bg-sky-950 rounded-lg p-6">
      <div className="flex items-center justify-between">
        <Link
          to={`/book/${book.id}`}
          className="font-semibold text-white hover:text-blue-600 transition duration-300 ease-in-out"
        >
          {book.title}
        </Link>
        <div
          className="flex justify-around h-10"
          onMouseEnter={() => setIsHovered(true)}
          onMouseLeave={() => setIsHovered(false)}
        >
          {isHovered ? (
            <div className="grid grid-rows-3 grid-flow-col gap-6">
              <button
                className="font-semibold text-green-900 hover:text-green-500"
                onClick={() => {
                  /*#TODO MOCKED NEED TO IMPLEMENT*/
                  window.location.reload()
                }}
              >
                Update
              </button>
              <button
                className="font-semibold text-red-900 hover:text-red-500"
                onClick={() => {
                  deleteBookById(book.id).then(() => {
                    window.location.reload()
                  })
                }}
              >
                Delete
              </button>
            </div>
          ) : (
            <img src={threeDots} alt="threeDots" className="size-8" />
          )}
        </div>
      </div>
      <p className="text-xs leading-5 text-gray-500">
        by {book.author.firstName} {book.author.secondName}
      </p>
      <div className="mt-2">
        <p className="text-xs leading-5">
          <span className="text-lg text-yellow-600">
            {book.review.rating} ⭐
          </span>{" "}
          <span className="text-xs text-gray-500">
            {getDateFromId(book.id)}
          </span>
        </p>
      </div>
      <div className="mt-2">
        <p className="text-sm leading-6 text-gray-400">{book.review.comment}</p>
      </div>
    </div>
  )
}

export default BookCard
